version: '3'

volumes:
  static:

services:
  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/backend_static
  frontend:
    build: ./frontend/
    volumes:
      - static:/frontend_static
  gateway:
    build: ./gateway/
    ports:
      - 9001:80
    volumes:
      - static:/staticfiles/
